language: python
python:
- '2.7'
env:
  global:
  - DJANGO_SETTINGS_MODULE='settings.testing'
install:
- pip install -q -r requirements.txt
- pip install -q python-coveralls
- pip install -q coverage
script:
- python waitress/manage.py collectstatic --noinput
- python waitress/manage.py makemigrations
- python waitress/manage.py migrate
- python waitress/manage.py test
after_success:
- coveralls
deploy:
  provider: openshift
  user:
    secure: uBWr1763wuA75QOP9IpCnJJ95xjNvxNSgHl2wWZWjPljl/cUNquSUUDgH0fs4Ec0zXza/LRgqHv0IkK5xqvLUvvw5NECzNQtQipKzC09zig/57KNO3D6RhsNJ3CxmdufZLM1jOs/AXvCIBuvPgftng/7OBLQow3k1mIBvY+MBeNov+zyLZjwpcqOd2Okj0MDncFSrv+pHDFiTpexT2LlX0I9ASgM0yp+5UKke6OstfQ36777/qIoziGYUupMG5hrg1gqB19QGbr7Nb8vXZfYnB3/3OA8Zkcv8+Hpk3MzAcpdE3jkPODJPbOMKPeg999xbw66Q9G0OZ9+b4Az2uJJJ5IILZt2UpFuPXqVH4Ez4CnJoNiav9GhOW8BKWTcBNpomfgf+peHVfdOKYUQgNnh2DXhEHnKtQoxXRr6V6nAlT/ylDw6yvMPWXeey9177PKf7ordxCUc1xd+VsanXe7BcPshOi2p90Pp8BigC5w5ohX3Tq5EVdsBt6KgmUmMGuR+OqLEKUFQwO4PqIOX9MhTaMVL8b5Fr6PqW993Qqblaj0hBfA326TaaET8UZkEXZTHwe4cfXY6jY2kmjU8cQKmjGbYrHVkMXlInOZBJ7dCG+AyvpCcfx4hzflr+mJ+h19TQy9B7N8ESKEzAU4DrpjnbF1Q8C2vkBswW39gasHxxCU=
  password:
    secure: NRZyHq+c9QdSbgGtm0oBTgkCfF8hpyMQBqJWFfw2q8B1K3z8JVgLIu8dRMCE/V5/6XGtFE+F7ks4XQG+/VzPopkk04M2DWAPFSjxGIosnG54jOvH5MADexkzSMIhqIJN6gURNkviSQSCE4mv7aQmgoh5XA8mpWJLgbm/wn+AX8hR5PjGS5qG+j5oi+kOpv+Dbl5QV7+RplLLt0ohgh/sBbFPpPfJsgS25GMD7L0QZoEbMmQARW4y9IUOIgp5YSyWuYy4OipexqZxUMjeRLJUtkRrbEUw0rv2qES/aL/TalMLAjv7zmKQVBD8XIDrcRSRF5A8iEqMgtbTSBH9alggyQEh7ZDqCxuDLimhHP27dEDtaz7PSXOIt/ffFb9GZe3Lrl2wArKY7+z9Gx69uic+kP4dbIp/bNMDUdlFj7vpr7TJGUIE6m9X/Vu4fPneiSpB2QM++fE69vdb+lXPWmqpvMMq4IgKUZkO3aP+kFuzCguY5L4Xf05OPhxf7Qcw+khzgYGRZ+bh3cKFczfHtMoC7rzQQsU7gtqMrEPSMrAlK3kN/aMO4GkFVyUqAIMceT2L4VxU2MrFY3gzTqZucG5p4S3vBgkK+mF0H8nOMy6X7XXYZmW3XXWJoqNOnuQqqkwbL7B6u6w1ZI+F/uMtWivUc+GrAMVHPW79yspU3okt5Gw=
  app: waitress
  domain:
    secure: woN338yhtgDiO3ROYLVG+O42zHUhGZhM8Dw1Kdd+pA1+eONVq1/DfgLgrN0Em6+oYe3RPVvFlVA0rTHHmYsgH+u3HNCeZdymrUz7tZGZdILlLTVzqMrW0W/XuMUYehMaxriy6Eck+57OjBK4IMuFXSxyaqT0ohwfTSVBQVC6kia7pxtu4knoPPlGAbNIEFSFSnLQYDJvUcM9vI+BOUONRsB1eZgpr2QlfqwPGHsPqckDhKZksqwPlRSoEx9QAfjzEFD3yHxKQyAtHQ5HsHZm+olyd/qXJter9wqCranWyD11ymMSF4X+gQKh7asWVP/DP90g49CkOBJLWQu+oPCVxVWardbA7t2n18fvcaeSGf6ULff0t4UKNZ5dQDGwAQukf/2VSQhOrMycPgBjrIlfcKMGMf1KpG5PZw1h/CzT7xwZdS6HuRXe84AQetOxkM3dHYZRHmqjyBD3joNbGJ8h7+g5K9mLXgd6av0vxUsNjL2o/3SoLbs+fcbuqRRpR9KD34dTF/lJg1HSe89/2qp0bj7Pb+NpnfoH7AiV4WYZpFL4go2O0RDYN0vm7CcNXUbEAIcdCY5Xl7amDCn3Ycrl3nOa1nfmj+hW1ldXh8Y4CRDzbiW25swAVi77Lrl4pIEycO+x293yVmoSDixW8SsCJk5uTWmso+j4VM8uN5B0AAs=
  on:
    repo: waitress-andela/waitress
